src/validators/mainnet.json

Description update for rhinostake validator

RHINO Description Update

---

src/validators/mainnet.json

thj has set up a new server so we'd like to add metadata for it. to avoid confusion we also change the name and description of existing node.

change the id of thj and add a new metadata for existing validator

---

src/validators/mainnet.json

We've updated the description to add missing info.

Update Validator: Luganodes powered by Infrared

---

src/tokens/bepolia.json
src/validators/bepolia.json
src/vaults/bepolia.json

Adding lists for the brand new best testnet in the world of testnets

feat: add bepolia lists

---

src/validators/mainnet.json

Update mainnet metadata

---

src/validators/mainnet.json

Add P2P.org validator

---

src/validators/mainnet.json

Infrared validator by Pier Two

---

src/vaults/mainnet.json

@BrownBrownBear 
Add Smilee protocol metadata

Add Smilee protocol

---

README.md

Added links to readme
BREAKING CHANGE: 🧨 No
✅ Closes: #31

docs: ✏️ Updated README with link

---

scripts/validateImages.ts

Tells user the image size required

feat: 🎸 Adjusted validateImages for better clarity

---

CONTRIBUTING.md

Added updated asset size and naming guide for images

feat: 🎸 Updated Contirbuting.md

---

.github/CODEOWNERS

Turns out CODEOWNERS syntax was not valid. I think you can check this works because there's this icon on the branch files. I'll ask to someone from my team to approve it before @codingwithmanny does so I can check if I still can merge it without a codeowner approval 
This also needs updates on all other repo if true
Before this goes in, we should make sure that frontend and backend team can bypass this check otherwise we wont be able to push hot fixes in case of emergency

updates codeowners

---

pnpm-lock.yaml
scripts/validateOnChainData/main.ts
src/tokens/mainnet.json
src/vaults/mainnet.json

Adds warnings instead of errors on specific address verifications and token names as some are the middle of getting changed

ci: 🎡 Fixed CI process for validation

---

src/vaults/mainnet.json

As per PRs #200 and #201, I have made the changes requested in them, and updated Concrete Vault URLs.

Update Concrete vault URLS, & Euler & Concrete logos

---

src/vaults/mainnet.json

Checking through and updating vault metadata as per the list from Pong today. Opening this PR now so Kodiak can also contribute if possible.

Update Remaining Vaults Metadata

---

src/vaults/mainnet.json

- fixes casing issue on protocol

chore: update casingo on protocol

---

src/vaults/mainnet.json

Smilee vaults metadata for NECT-wgBERA and WBERA-wgBERA were inverted

Fix Smilee vault metadata

---

scripts/validateOnChainData/_tokens.ts
scripts/validateOnChainData/_vaults.ts
scripts/validateOnChainData/main.ts

This PR differentiates the level of errors and blocks PR from being merged if errors are found in CI.
Warnings won't be blocking

fix: restore validation enforcement

---

schemas/vaults.schema.json
scripts/types.ts

Updating the schema as discussed yesterday.
This is not required for now but will be in the future

feat(vaults): add action property

---

src/vaults/bepolia.json

- remove bepolia val 6
- update bepolia val 1 & 2 desc

chore: update bepolia val metadata

---

src/validators/mainnet.json

Updated logo (padding added) and website link for L0vd validator.

Modify L0vd validator details in mainnet.json
